# Table of Contents
 <p><div class="lev1"><a href="#Task-1.-Compiling-Ebola-Data"><span class="toc-item-num">Task 1.&nbsp;&nbsp;</span>Compiling Ebola Data</a></div>
 <div class="lev1"><a href="#Task-2.-RNA-Sequences"><span class="toc-item-num">Task 2.&nbsp;&nbsp;</span>RNA Sequences</a></div>
 <div class="lev1"><a href="#Task-3.-Class-War-in-Titanic"><span class="toc-item-num">Task 3.&nbsp;&nbsp;</span>Class War in Titanic</a></div></p>

In [3]:
import pandas as pd

In [ ]:
DATA_FOLDER = '' # Use the data folder provided in Tutorial 02 - Intro to Pandas.

## Task 1. Compiling Ebola Data

The `DATA_FOLDER/ebola` folder contains summarized reports of Ebola cases from three countries (Guinea, Liberia and Sierra Leone) during the recent outbreak of the disease in West Africa. For each country, there are daily reports that contain various information about the outbreak in several cities in each country.

Use pandas to import these data files into a single `Dataframe`.
Using this `DataFrame`, calculate for *each country*, the *daily average per month* of *new cases* and *deaths*.
Make sure you handle all the different expressions for *new cases* and *deaths* that are used in the reports.

In [ ]:
# Write your answer here

## Task 2. RNA Sequences

In the `DATA_FOLDER/microbiome` subdirectory, there are 9 spreadsheets of microbiome data that was acquired from high-throughput RNA sequencing procedures, along with a 10<sup>th</sup> file that describes the content of each. 

Use pandas to import the first 9 spreadsheets into a single `DataFrame`.
Then, add the metadata information from the 10<sup>th</sup> spreadsheet as columns in the combined `DataFrame`.
Make sure that the final `DataFrame` has a unique index and all the `NaN` values have been replaced by the tag `unknown`.

## Solution

To solve this exercice we will first load the metadata and modify the NA value to the *unknown* tag. After that we will load every MIDx.xls file in a separate DataFrame and store them in a list to be able to concat them together. While we load the files we will add a new column call *BARCODE* and store which file every row comes from. This will allow us to use a simple merge to fill the metadatas in for each line. Finaly to keep unique indexes we will use the tupple [*BARCODE, TAXON*]

In [4]:
DATA_FOLDER = 'Data/microbiome/'
METADATA = 'metadata'
MID = 'MID'
XLS = '.xls'

In [5]:
metadata = pd.read_excel(DATA_FOLDER + METADATA + XLS).fillna('unknown')
metadata

  BARCODE               GROUP   SAMPLE
0    MID1  EXTRACTION CONTROL  unknown
1    MID2               NEC 1   tissue
2    MID3           Control 1   tissue
3    MID4               NEC 2   tissue
4    MID5           Control 2   tissue
5    MID6               NEC 1    stool
6    MID7           Control 1    stool
7    MID8               NEC 2    stool
8    MID9           Control 2    stool

In [6]:
temp_df_list = []
for x in range(9):
    temp_df = pd.read_excel(DATA_FOLDER + MID + str(x+1) + XLS, header=None)
    temp_df['BARCODE'] = pd.Series([MID + str(x+1)]*len(temp_df))
    temp_df_list.append(temp_df)
taxons = pd.concat(temp_df_list)
taxons.columns = ['TAXON', 'COUNT', 'BARCODE']

taxons.head()

                                               TAXON  COUNT BARCODE
0  Archaea "Crenarchaeota" Thermoprotei Desulfuro...      7    MID1
1  Archaea "Crenarchaeota" Thermoprotei Desulfuro...      2    MID1
2  Archaea "Crenarchaeota" Thermoprotei Sulfoloba...      3    MID1
3  Archaea "Crenarchaeota" Thermoprotei Thermopro...      3    MID1
4  Archaea "Euryarchaeota" "Methanomicrobia" Meth...      7    MID1

In [7]:
final = taxons.merge(metadata, on='BARCODE', how='left').set_index(['BARCODE', 'TAXON'])
final.head()

                                                            COUNT  \
BARCODE TAXON
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...      7
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...      2
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...      3
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...      3
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...      7

                                                                         GROUP  \
BARCODE TAXON
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  EXTRACTION CONTROL
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  EXTRACTION CONTROL
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...  EXTRACTION CONTROL
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...  EXTRACTION CONTROL
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  EXTRACTION CONTROL

                                                             SAMPLE
BARCODE TAXON
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  unknown
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  unknown
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...  unknown
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...  unknown
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  unknown

In [8]:
final.tail()

                                                            COUNT      GROUP  \
BARCODE TAXON
MID9    Bacteria "Thermotogae" Thermotogae Thermotogale...     43  Control 2
        Bacteria "Thermotogae" Thermotogae Thermotogale...     16  Control 2
        Bacteria "Verrucomicrobia" Opitutae Opitutales ...      1  Control 2
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...      1  Control 2
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...     10  Control 2

                                                           SAMPLE
BARCODE TAXON
MID9    Bacteria "Thermotogae" Thermotogae Thermotogale...  stool
        Bacteria "Thermotogae" Thermotogae Thermotogale...  stool
        Bacteria "Verrucomicrobia" Opitutae Opitutales ...  stool
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...  stool
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...  stool

We can check that the index is unique and that there is no more NaN values

In [12]:
final.index.is_unique

True

In [14]:
final.isnull()

                                                            COUNT  GROUP  \
BARCODE TAXON
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  False  False
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...  False  False
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...  False  False
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...  False  False
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  False  False
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  False  False
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...  False  False
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...  False  False
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...  False  False
        Archaea "Euryarchaeota" Halobacteria Halobacter...  False  False
        Archaea "Euryarchaeota" Halobacteria Halobacter...  False  False
        Archaea "Euryarchaeota" Halobacteria Halobacter...  False  False
        Archaea "Euryarchaeota" Halobacteria Halobacter...  False  False
        Archaea "Euryarchaeota" Halobacteria Halobacter...  False  False
        Archaea "Euryarchaeota" Methanococci Methanococ...  False  False
        Archaea "Euryarchaeota" Methanopyri Methanopyra...  False  False
        Archaea "Euryarchaeota" Thermoplasmata Thermopl...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
        Bacteria "Actinobacteria" Actinobacteria Actino...  False  False
...                                                           ...    ...
MID9    Bacteria "Proteobacteria" Gammaproteobacteria O...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria O...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria O...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria P...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria T...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria T...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria T...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria T...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria X...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria X...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria X...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria X...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria X...  False  False
        Bacteria "Proteobacteria" Gammaproteobacteria X...  False  False
        Bacteria "Synergistetes" Synergistia Synergista...  False  False
        Bacteria "Tenericutes" Mollicutes Anaeroplasmat...  False  False
        Bacteria "Tenericutes" Mollicutes Haloplasmatal...  False  False
        Bacteria "Thermodesulfobacteria" Thermodesulfob...  False  False
        Bacteria "Thermodesulfobacteria" Thermodesulfob...  False  False
        Bacteria "Thermotogae" Thermotogae Thermotogale...  False  False
        Bacteria "Thermotogae" Thermotogae Thermotogale...  False  False
        Bacteria "Verrucomicrobia" Opitutae Opitutales ...  False  False
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...  False  False
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...  False  False

                                                            SAMPLE
BARCODE TAXON
MID1    Archaea "Crenarchaeota" Thermoprotei Desulfuroc...   False
        Archaea "Crenarchaeota" Thermoprotei Desulfuroc...   False
        Archaea "Crenarchaeota" Thermoprotei Sulfolobal...   False
        Archaea "Crenarchaeota" Thermoprotei Thermoprot...   False
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...   False
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...   False
        Archaea "Euryarchaeota" "Methanomicrobia" Metha...   False
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...   False
        Archaea "Euryarchaeota" Archaeoglobi Archaeoglo...   False
        Archaea "Euryarchaeota" Halobacteria Halobacter...   False
        Archaea "Euryarchaeota" Halobacteria Halobacter...   False
        Archaea "Euryarchaeota" Halobacteria Halobacter...   False
        Archaea "Euryarchaeota" Halobacteria Halobacter...   False
        Archaea "Euryarchaeota" Halobacteria Halobacter...   False
        Archaea "Euryarchaeota" Methanococci Methanococ...   False
        Archaea "Euryarchaeota" Methanopyri Methanopyra...   False
        Archaea "Euryarchaeota" Thermoplasmata Thermopl...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
        Bacteria "Actinobacteria" Actinobacteria Actino...   False
...                                                            ...
MID9    Bacteria "Proteobacteria" Gammaproteobacteria O...   False
        Bacteria "Proteobacteria" Gammaproteobacteria O...   False
        Bacteria "Proteobacteria" Gammaproteobacteria O...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria P...   False
        Bacteria "Proteobacteria" Gammaproteobacteria T...   False
        Bacteria "Proteobacteria" Gammaproteobacteria T...   False
        Bacteria "Proteobacteria" Gammaproteobacteria T...   False
        Bacteria "Proteobacteria" Gammaproteobacteria T...   False
        Bacteria "Proteobacteria" Gammaproteobacteria X...   False
        Bacteria "Proteobacteria" Gammaproteobacteria X...   False
        Bacteria "Proteobacteria" Gammaproteobacteria X...   False
        Bacteria "Proteobacteria" Gammaproteobacteria X...   False
        Bacteria "Proteobacteria" Gammaproteobacteria X...   False
        Bacteria "Proteobacteria" Gammaproteobacteria X...   False
        Bacteria "Synergistetes" Synergistia Synergista...   False
        Bacteria "Tenericutes" Mollicutes Anaeroplasmat...   False
        Bacteria "Tenericutes" Mollicutes Haloplasmatal...   False
        Bacteria "Thermodesulfobacteria" Thermodesulfob...   False
        Bacteria "Thermodesulfobacteria" Thermodesulfob...   False
        Bacteria "Thermotogae" Thermotogae Thermotogale...   False
        Bacteria "Thermotogae" Thermotogae Thermotogale...   False
        Bacteria "Verrucomicrobia" Opitutae Opitutales ...   False
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...   False
        Bacteria Cyanobacteria Cyanobacteria  Chloropla...   False

[2396 rows x 3 columns]

## Task 3. Class War in Titanic

Use pandas to import the data file `Data/titanic.xls`. It contains data on all the passengers that travelled on the Titanic.

In [ ]:
from IPython.core.display import HTML
HTML(filename=DATA_FOLDER+'/titanic.html')

For each of the following questions state clearly your assumptions and discuss your findings:
1. Describe the *type* and the *value range* of each attribute. Indicate and transform the attributes that can be `Categorical`. 
2. Plot histograms for the *travel class*, *embarkation port*, *sex* and *age* attributes. For the latter one, use *discrete decade intervals*. 
3. Calculate the proportion of passengers by *cabin floor*. Present your results in a *pie chart*.
4. For each *travel class*, calculate the proportion of the passengers that survived. Present your results in *pie charts*.
5. Calculate the proportion of the passengers that survived by *travel class* and *sex*. Present your results in *a single histogram*.
6. Create 2 equally populated *age categories* and calculate survival proportions by *age category*, *travel class* and *sex*. Present your results in a `DataFrame` with unique index.

In [ ]:
# Write your answer here